import Link from 'next/link';import ProductGrid from '@/components/ProductGrid';import {products} from '@/data/products';
const cats=[['Women’s Perfumes','Women','womens-perfume-final.jpg'],['Men’s Perfumes','Men','mens-perfume-final.jpg'],['Unisex Perfumes','Unisex','unisex-perfume.jpg'],['New Arrivals','new','new-arrivals-perfume.jpg'],['Budget Perfumes','budget','budget-perfumes-final.jpg']];
const featuredBrands=['Lattafa','Maison Asrar','Paris Corner','Khadlaj','Rayhaan','Zimaya','Armaf','Fragrance World','Pendora Scents','Maison Alhambra','French Avenue','Gulf Orchid'];
export default function Home(){return <>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">Authentic Dubai Perfumes</p><h1>Find Your<br/><em>Signature Scent</em></h1><p>Discover beautiful fragrances carefully selected to make every moment unforgettable.</p></div><div className="hero-visual"><img src="/images/logo/Hero%20image%203.png" alt="Sentique Perfumes hero artwork"/></div></section>
 <section className="section"><div className="section-heading"><div><p className="eyebrow">Explore the collection</p><h2>Shop by category</h2></div><p>Find a fragrance for every mood, moment and story.</p></div><div className="category-grid">{cats.map(([name,key,img])=><Link className="category" href={['new','best','budget'].includes(key)?`/shop?special=${key}`:`/shop?category=${key}`} key={name}><img src={`/images/categories/${img}`} alt=""/><span><b>{name}</b><small>Discover the edit →</small></span></Link>)}</div></section>
 <section className="section tinted"><div className="section-heading"><div><p className="eyebrow">Loved by you</p><h2>Featured perfumes</h2></div><Link href="/shop">View all fragrances →</Link></div><ProductGrid products={products.slice(0,4)}/></section>
 <section className="story" id="about"><div className="story-image"><img src="/images/logo/Hero%20image%203.png" alt="Sentique Perfumes hero artwork"/></div><div><p className="eyebrow">Our story</p><h2>About Sentique Perfumes</h2><p>At Sentique Perfumes, we believe fragrance is more than something you wear — it becomes part of your story.</p><p>We carefully select beautiful fragrances for men and women, from everyday favourites to distinctive scents made for unforgettable occasions.</p><p>Our goal is simple: exceptional fragrances, personal service and a shopping experience you’ll want to return to.</p><Link className="text-link" href="/contact">Meet Sentique →</Link></div></section>
 <section className="section"><div className="center-heading"><p className="eyebrow">The Sentique difference</p><h2>Why shop with Sentique?</h2></div><div className="benefits">{[['◇','Authentic Fragrances','Carefully selected perfumes from trusted suppliers.'],['♡','Personal Service','Friendly, personal assistance when choosing your fragrance.'],['⌁','Fast Delivery','Convenient delivery options throughout South Africa.'],['◉','Easy WhatsApp Ordering','Order your favourite fragrances directly through WhatsApp.']].map(x=><div key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
 <section className="section sage"><div className="section-heading"><div><p className="eyebrow">Freshly discovered</p><h2>New arrivals</h2></div><Link href="/shop?special=new">Shop new arrivals →</Link></div><ProductGrid products={products.filter(p=>p.newArrival&&p.created>=12&&!['010','011','013'].includes(p.id)).sort((a,b)=>b.created-a.created)}/></section>
 <section className="section"><div className="center-heading"><p className="eyebrow">Find your favourite</p><h2>Shop your favourite brands</h2></div><div className="brands">{featuredBrands.map(b=><Link href={`/shop?brand=${encodeURIComponent(b)}`} key={b}>{b}</Link>)}</div></section>
 <section className="testimonials"><div className="center-heading"><p className="eyebrow">Kind words</p><h2>What Our Customers Say</h2></div><div className="reviews">{[['“The packaging was beautiful and the fragrance is even better. Sentique helped me find my new everyday scent.”','Naledi M.'],['“Warm, personal service and such an easy WhatsApp order. My perfume arrived beautifully wrapped.”','Ayesha K.'],['“An exquisite selection. I have already ordered twice and every scent feels so special.”','Thandi P.']].map(x=><blockquote key={x[1]}><div>★★★★★</div><p>{x[0]}</p><cite>— {x[1]}</cite></blockquote>)}</div></section>
 <section className="section social"><div className="center-heading"><p className="eyebrow">@sent_iqueperfumes</p><h2>Follow Sentique Perfumes</h2></div><div className="social-follow-grid"><a className="social-follow-card instagram-card" href="https://www.instagram.com/sent_iqueperfumes?utm_source=qr" target="_blank" rel="noreferrer" aria-label="Follow Sentique Perfumes on Instagram"><span className="social-icon">◎</span><span className="social-name">Instagram</span><strong>@sent_iqueperfumes</strong><span className="social-follow-button">Follow on Instagram</span></a><a className="social-follow-card tiktok-card" href="https://www.tiktok.com/@sent_iqueperfumes" target="_blank" rel="noreferrer" aria-label="Follow Sentique Perfumes on TikTok"><span className="social-icon">♪</span><span className="social-name">TikTok</span><strong>@sent_iqueperfumes</strong><span className="social-follow-button">Follow on TikTok</span></a></div></section>
 <section className="newsletter"><p className="eyebrow">A note from Sentique</p><h2>Discover something beautiful</h2><p>Be first to hear about new arrivals, scent stories and special edits.</p><form><label className="sr-only" htmlFor="newsletter">Email address</label><input id="newsletter" type="email" placeholder="Your email address"/><button className="button">Join our list</button></form></section>
 </>}
